dataset_path: data/ #Relative path to the data directory.
sampling_config: #Controls how training samples are created from the raw data.
  window_length_lookback: 12 #Number of 5-second intervals to look back (e.g., 12 = 1 minute).
  window_length_outlook: 12 #Number of 5-second intervals to look ahead (e.g., 12 = 1 minute).
  pi_list:
    - Shot
    - BP
    - BP3rd
    - BPBox
    - Goal
    - Cross
    - PassBox
    - Pass3rd
    - Corner
    - TackWon
    - Danger
    - OutpOpp
    - Shot_diff
    - BP_diff
    - BP3rd_diff
    - BPBox_diff
    - Goal_diff
    - Cross_diff
    - PassBox_diff
    - Pass3rd_diff
    - Corner_diff
    - TackWon_diff
    - Danger_diff
    - OutpOpp_diff
    - EntrBox
    - Entr3rd
    - EntrBox_diff
    - Entr3rd_diff
  training_goal: Goal #Shot, Cross, Corner, Entr3rd
  folding: [ 'any_above', 0 ]
  hidden: 12 #hidden period between lookback and outlook (e.g., 12 = 1 minute gap).
  sample_rate: 1 #Downsampling rate (1 = no downsampling).
  split: [ 0.6, 0.2, 0.2 ] #Train/val/test split as fractions (must sum to 1.0).
  normalize: True     # Normalizing features to a [0,1] range. The scaler is fitted to the training data and subsequently applied to the validation and test sets
  parallelize: False   #reading the data parallel on multiple threads
  split_in_matches: False  #decide whether data split happens within matches (TRUE) or across matches (FALSE)
  random_folds: True #if split_in_matches: True than random_folds: False, if split_in_matches: False than both is possible
mode: classification
pi_config_list: # Defines sets of PIs used for individual model runs. Can be single PI ([ Shot ]) or combinations ([ Shot, BP ]). Each set defines a separate model training run using the specified PIs.
  - [ Shot ]
  - [ BP ]
  - [ BP3rd ]
  - [ BPBox ]
  - [ Goal ]
  - [ Cross ]
  - [ PassBox ]
  - [ Pass3rd ]
  - [ Corner ]
  - [ TackWon ]
  - [ Danger ]
  - [ OutpOpp ]
  - [ Shot_diff ]
  - [ BP_diff ]
  - [ BP3rd_diff ]
  - [ BPBox_diff ]
  - [ Goal_diff ]
  - [ Cross_diff ]
  - [ PassBox_diff ]
  - [ Pass3rd_diff ]
  - [ Corner_diff ]
  - [ TackWon_diff ]
  - [ Danger_diff ]
  - [ OutpOpp_diff ]
  - [ EntrBox ]
  - [ Entr3rd ]
  - [ EntrBox_diff ]
  - [ Entr3rd_diff ]  #individual PI as single input
  - [ Shot, BP ] #individual PIs as multiple inputs
  - [ BP, Cross ]
models: # Specifies which models to train and their hyperparameters.
  LogisticRegressionClassifier:
    model_config:
      class_weight: balanced
      n_jobs: -1
  NBClassifier:
    model_config: {}
  SVMClassifier:
    model_config:
      class_weight: balanced
  KNNClassifier:
    model_config:
      n_neighbors: 2
      weights: distance
      n_jobs: 32      
  RandomGuesser:
    model_config: {}
  # Note NNClassifier requires consistent input shape across pi_config_list entries. Use only when all sets have the same number of PIs.
  #NNClassifier:
  # model_config:
  #    model_config:
  #      num_channels: 2    #Number of PIs per pi_config_list entry
  #      time_steps: 12 #same number like window_length_lookback
  #      class_weights: { 0: 1, 1: 1 }
  #      lr: 0.001
  #      dropout_probability: 0.4
  #      classification: True
  #    batch_size: 32
  #    sampling: balanced_best
  #    trainer_config:
  #      max_epochs: 5
  #      enable_progress_bar: False
  #      enable_model_summary: None
  #    gpus: 1
save_models: False #Whether trained models should be saved to disk.
output_dir_path: output #Directory where results, logs, or saved models (if enabled) will be stored.
